# Generated by Django 6.0.5 on 2026-05-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Подробное описание'),
        ),
    ]
